version: '2'
services:
    # MYSQL
    mysql:
        image: mysql:5.7
        container_name: mysql
        env_file:
            - ${BASE_DIR}/dev/mysql.env
        volumes:
            - ${BASE_DIR}/storage/mysql:/var/lib/mysql
        networks:
            - database
