version: '2'
services:
    # MYSQL
    mysql:
        image: mysql:5.7
        container_name: mysql
        env_file:
            - ./dev/mysql.env
        volumes:
            - ./storage/mysql:/var/lib/mysql
        networks:
            - database
    # NGINX
    web:
      image: eu.gcr.io/clevmindblog/blog:v2
      container_name: blog
      ports:
       - "80:80"
      volumes:
       - ./website:/var/www/blog
       - ./storage/app:/var/www/blog/storage/app
       - ./storage/logs:/var/www/blog/storage/logs
      links:
        - mysql
        - redis
      networks:
        - server
        - database
    # REDIS
    redis:
      container_name: redis
      image: redis:latest
      ports:
        - "6379:6379"
      networks:
          - server

networks:
    database:
    server:
