kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: blog
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: nginx
        image: eu.gcr.io/clevmindblog/blog/blog:v3
        imagePullPolicy: Always
        ports:
        -  containerPort: 80
        env:
        - name: APP_ENV
          value: "production"
      - name: redis
        image: redis:latest
        ports:
        -  containerPort: 6379
